/*
 * MIT License (MIT)
 * Copyright (c) 2019 Activeledger
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { IKey, KeyType } from "@activeledger/sdk-core";

// Extends IKey with the BIP-39 recovery phrase - kept local to this
// package (duplicated in sdk-node too) rather than added to sdk-core, since
// the BIP-39 feature itself lives entirely in the platform packages.
export interface IKeyExtended extends IKey {
  phrase?: string;
}

// (duplicated in sdk-node too, alongside IKeyExtended)
export interface IBIP39Options {
  compressed?: boolean;
  /** Optional BIP-39 passphrase ("25th word"). Ignored when legacy is true. */
  passphrase?: string;
  /**
   * Use the original @activeledger/sdk-bip39 package's scheme -
   * SHA256(phrase) directly as the private key, no KDF, no domain
   * separation - instead of the standard BIP-39 seed + BIP-32 master-key
   * derivation used by default. Only for recovering a phrase that was
   * already generated by that package; do not use it for new keys.
   */
  legacy?: boolean;
  /**
   * Which kind of key to derive. Defaults to secp256k1, which is what this
   * method produced before the post-quantum types existed - so a phrase
   * generated by an earlier version still recovers the same identity.
   *
   * Each type gets its own seed from the phrase, so one phrase can back a
   * secp256k1, an ml-dsa-65 and a falcon-512 identity at once without any of
   * them revealing the others.
   */
  type?: KeyType;
  /**
   * Set false to skip mnemonic validation.
   *
   * The phrase is checked by default - wordlist and checksum - because an
   * unchecked one does not fail loudly: a typo derives a different VALID key
   * for an identity nobody owns.
   *
   * Versions before 2.4.0 never checked, so pass false if you relied on
   * deriving from a string that is not a BIP-39 mnemonic. Ignored when
   * `legacy` is true, which never involved a mnemonic.
   */
  validate?: boolean;
}
