/*
 * MIT License (MIT)
 * Copyright (c) 2019 Activeledger
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { generateMnemonic, mnemonicToSeedSync } from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english.js";
import { hmac } from "@noble/hashes/hmac.js";
import { hkdf } from "@noble/hashes/hkdf.js";
import { sha256, sha512 } from "@noble/hashes/sha2.js";
import { secp256k1 } from "@noble/curves/secp256k1.js";
import { KeyHandler as CoreKeyHandler, KeyType } from "@activeledger/sdk-core";
import { IBIP39Options, IKeyExtended } from "./interfaces.js";
import { fromHex, toHex, WebCryptoProvider } from "./crypto.js";

const textEncoder = new TextEncoder();

/**
 * Adds BIP-39 recovery-phrase key generation to the core KeyHandler.
 *
 * @export
 * @class KeyHandler
 */
export class KeyHandler extends CoreKeyHandler {
  /** Kept here as well as passed up, since the base class holds it privately. */
  private readonly provider: WebCryptoProvider;

  constructor() {
    const provider = new WebCryptoProvider();
    super(provider);
    this.provider = provider;
  }

  /**
   * Generate a new key with a BIP-39 recovery phrase.
   *
   * @param {string} keyName - The name of the key
   * @param {IBIP39Options} [options]
   * @returns {Promise<IKeyExtended>}
   * @memberof KeyHandler
   */
  public generateBIP39Key(keyName: string, options?: IBIP39Options): Promise<IKeyExtended> {
    return this.restoreBIP39Key(keyName, generateMnemonic(wordlist), options);
  }

  /**
   * Recreate a key from a previously generated BIP-39 recovery phrase.
   *
   * By default, the private key is derived the standard way - a BIP-39
   * PBKDF2 seed, then just the BIP-32 master-key step (HMAC-SHA512 keyed
   * with "Bitcoin seed", left 32 bytes) - deliberately stopping there
   * rather than doing any further hierarchical (HD) child derivation,
   * since Activeledger attaches many independent keys to one identity
   * rather than deriving them from a single tree. Matches
   * @activeledger/sdk-node's default derivation exactly - a phrase
   * generated on one platform recovers the identical key on the other.
   *
   * `options.legacy: true` instead reproduces the original
   * @activeledger/sdk-bip39 package's scheme - SHA256(phrase) used
   * directly as the private key, with no KDF or domain separation - only
   * for recovering a phrase that was already generated by that (Node-only)
   * package. Do not use it for new keys.
   *
   * @param {string} keyName - The name of the key
   * @param {string} phrase - The recovery phrase
   * @param {IBIP39Options} [options]
   * @returns {Promise<IKeyExtended>}
   * @memberof KeyHandler
   */
  public restoreBIP39Key(keyName: string, phrase: string, options: IBIP39Options = {}): Promise<IKeyExtended> {
    return new Promise((resolve, reject) => {
      try {
        const type = options.type || KeyType.EllipticCurve;

        if (options.legacy && type !== KeyType.EllipticCurve) {
          // The legacy scheme produces a 32-byte scalar and nothing else.
          // Silently ignoring it for a post-quantum type would hand back a
          // key from the modern derivation while the caller believed they
          // were recovering an old one.
          return reject(
            new Error(`The legacy BIP-39 scheme is secp256k1 only - it cannot derive ${type}`)
          );
        }

        const seed = options.legacy
          ? sha256(textEncoder.encode(phrase))
          : this.deriveSeed(type, mnemonicToSeedSync(phrase, options.passphrase || ""));

        const keyHolder: IKeyExtended = {
          key: this.provider.generateFromSeed(seed, options.compressed, type),
          name: keyName,
          type,
          phrase,
        };

        resolve(keyHolder);
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Turn a BIP-39 seed into the seed the requested algorithm takes.
   *
   * Byte-for-byte identical to sdk-node's, and the secp256k1 branch must
   * never change: both packages have shipped it since before the
   * post-quantum types existed, so phrases are already in use. Moving it
   * onto HKDF would hand every one of those users a different key for a
   * phrase that used to work - not an error, just an identity that is no
   * longer theirs.
   *
   * Published, with vectors, in vectors/seed-vectors.json.
   *
   * @private
   */
  private deriveSeed(type: KeyType, bip39Seed: Uint8Array): Uint8Array {
    if (type === KeyType.EllipticCurve) {
      return this.deriveBIP32MasterKey(bip39Seed);
    }

    const length = type === KeyType.Falcon512 ? 48 : 32;

    // An empty salt is a block of zero bytes of the hash length - what RFC
    // 5869 specifies, and what node's crypto.hkdfSync does, so the two
    // packages agree byte for byte.
    return hkdf(sha512, bip39Seed, new Uint8Array(0), textEncoder.encode(`activeledger-seed-v1:${type}`), length);
  }

  /**
   * BIP-32's master key generation step (the root of the HD tree), applied
   * to a BIP-39 seed - and nothing past that root, since no child paths are
   * derived here.
   *
   * @private
   * @param {Uint8Array} seed
   * @returns {Uint8Array} the 32-byte master private key
   */
  private deriveBIP32MasterKey(seed: Uint8Array): Uint8Array {
    return hmac(sha512, textEncoder.encode("Bitcoin seed"), seed).subarray(0, 32);
  }
}
