// Generates the canonical NUMBER vectors.
//
// What gets signed is `JSON.stringify($tx)`, and the ledger verifies by
// re-stringifying the $tx it parsed. So JavaScript's number formatting is not
// a convention this SDK happens to follow - it is the specification, and a
// port that formats a number differently produces a signature the ledger
// rejects as 1220 "Signature Incorrect" while saying nothing about numbers.
//
// This file exists because the existing `float` vector - 1, 0.1, -2.5, 0 -
// sits entirely inside the range where every language already agrees. Six of
// the seven SDKs disagreed with JavaScript outside it, and nothing caught it:
//
//   input     JS        PHP           Python        Go         Rust
//   1e21      1e+21     1.0e+21       1000...000    1e+21      1000...000
//   1e-7      1e-7      1.0e-7        1e-07         1e-07      0.0000001
//   -0        0         0             0             -0         0
//
// Regenerate with: npm run vectors:numbers
//
// THE RULE, from ECMA-262 Number::toString:
//
//   - Negative zero prints as "0", not "-0".
//   - Plain decimal while the decimal exponent n satisfies -6 < n <= 21.
//     So 1e20 is 100000000000000000000 and 1e-6 is 0.000001, but 1e21 and
//     1e-7 cross into exponent form.
//   - Exponent form has NO leading zeros in the exponent - "1e-7", never
//     "1e-07" - and an explicit "+" when positive: "1e+21".
//   - The digits are the SHORTEST decimal that round-trips to the same
//     double. Not 17 digits, not %g's default 6.

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, "..", "vectors", "number-vectors.json");

// Chosen to hit every branch of the algorithm and both sides of each
// boundary, because the boundaries are where implementations part company.
const CASES = [
  ["zero", 0], ["negative-zero", -0], ["one", 1], ["negative-one", -1],
  ["trailing-zero-dropped", 1.5], ["tenth", 0.1], ["negative-fraction", -2.5],
  ["thousandth", 0.001],

  // The plain/exponent boundary on the large side: 1e20 stays plain, 1e21 does not.
  ["int-1e19", 1e19], ["int-1e20", 1e20], ["int-1e21", 1e21], ["int-1e22", 1e22],

  // And on the small side: 1e-6 stays plain, 1e-7 does not.
  ["small-1e-5", 1e-5], ["small-1e-6", 1e-6], ["small-1e-7", 1e-7],
  ["small-1e-21", 1e-21], ["negative-small", -1.5e-9],

  // Integers at the edge of exact representation.
  ["max-safe-integer", 9007199254740991], ["beyond-safe-integer", 9007199254740992],

  // Shortest-round-trip cases: a naive 17-digit or %g formatter fails these.
  ["full-precision", 0.1234567890123456789], ["one-third", 1 / 3],
  ["large-fraction", 1234567890123456789.5],

  // The extremes of the double range.
  ["max-double", Number.MAX_VALUE], ["min-double", Number.MIN_VALUE],
];

const HEADER = [
  "Canonical NUMBER formatting for Activeledger SDKs.",
  "",
  "Generated by scripts/number-vectors.mjs. Do not hand-edit.",
  "",
  "What gets signed is JSON.stringify($tx), and the ledger verifies by",
  "re-stringifying the $tx it parsed. JavaScript's number formatting is",
  "therefore the SPECIFICATION, not a convention - a port that formats a",
  "number differently produces a signature the ledger rejects as 1220",
  "\"Signature Incorrect\", with nothing in the message about numbers.",
  "",
  "THE RULE, from ECMA-262 Number::toString:",
  "",
  "  - Negative zero prints as \"0\", never \"-0\".",
  "",
  "  - Plain decimal while the decimal exponent n satisfies -6 < n <= 21.",
  "    1e20 is 100000000000000000000 and 1e-6 is 0.000001; 1e21 and 1e-7",
  "    cross into exponent form. Both sides of both boundaries are here.",
  "",
  "  - Exponent form carries NO leading zeros in the exponent - \"1e-7\",",
  "    never \"1e-07\" - and an explicit \"+\" when positive: \"1e+21\".",
  "",
  "  - The digits are the SHORTEST decimal that round-trips to the same",
  "    double. Not 17 digits, and not %g's default of 6.",
  "",
  "This file exists because the `float` vector in pq-vectors.json - 1, 0.1,",
  "-2.5, 0 - sits entirely inside the range where every language agrees.",
  "Six of the seven SDKs disagreed with JavaScript outside it and nothing",
  "caught it, because a hand-written example is drawn from the same",
  "intuition that wrote the implementation.",
  "",
  "`value` is the input as a JSON number, so it parses to the same double",
  "everywhere. `expected` is exactly what must be emitted for it.",
];

const vectors = CASES.map(([name, value]) => ({
  name,
  value,
  expected: JSON.stringify(value),
}));

fs.writeFileSync(
  OUT,
  JSON.stringify({ header: HEADER.join("\n"), generated: new Date().toISOString(), vectors }, null, 2) + "\n",
);

console.log(`wrote ${path.relative(process.cwd(), OUT)} - ${vectors.length} number vectors`);
