// Generates the cross-language post-quantum test vectors that every
// non-JavaScript SDK checks itself against.
//
// The JS SDK is the reference implementation, so "correct" for a port means
// "agrees with this file". Publishing it as a committed artefact is what
// stops each port defining correctness by accident, and what lets a port
// author work without a running ledger.
//
// Regenerate with: npm run vectors
//
// KEY BYTES, NOT SEEDS - this matters and is not an arbitrary choice.
// ml-dsa-65 derives its key pair deterministically from a 32-byte seed, so a
// seed would be enough for it. falcon-512 does NOT: its key generation is
// implementation-specific, so the same seed produces different keys in
// different libraries. A seed-based vector file would therefore be unusable
// from Kotlin, Python or Go, which is precisely who it is for.

import { createRequire } from "module";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const { NodeCryptoProvider } = require("../packages/node/lib/index.js");

const provider = new NodeCryptoProvider();
const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, "..", "vectors", "pq-vectors.json");

const TYPES = ["ml-dsa-65", "falcon-512"];

// Each case is a $tx object. What actually gets signed is
// JSON.stringify($tx) encoded UTF-8 - no hash prefix, no length prefix, no
// key sorting - so these are chosen to catch the canonicalisation bugs that
// an ASCII-only integer payload cannot.
const MESSAGES = [
  // Baseline. Passes in every language even when everything below is broken.
  { name: "ascii", tx: { greeting: "hello" } },

  // Catches Python's json.dumps(ensure_ascii=True), which would emit \uXXXX
  // escapes and sign different bytes. An accented Latin letter, a CJK
  // character and an emoji - 2, 3 and 4 byte UTF-8 sequences respectively.
  { name: "non-ascii", tx: { greeting: "café 日本語 ☕" } },

  // Catches Go's encoding/json, which HTML-escapes <, > and & by default,
  // and any JVM JSON library configured the same way.
  { name: "html", tx: { expr: "a < b && c > d", amp: "Tom & Jerry" } },

  // Catches number formatting. JavaScript prints 1, not 1.0.
  { name: "float", tx: { whole: 1.0, third: 0.1, negative: -2.5, zero: 0 } },

  // Catches key reordering. The ledger does not canonicalise key order, so a
  // signer must reproduce insertion order exactly. These keys are
  // deliberately NOT alphabetical - a library that sorts will fail here.
  { name: "ordering", tx: { zebra: 1, alpha: 2, middle: 3 } },

  // A realistic onboarding body, closest to what a port sends first.
  {
    name: "onboard",
    tx: {
      $namespace: "default",
      $contract: "onboard",
      $i: { identity: { type: "ml-dsa-65", publicKey: "PLACEHOLDER" } },
      $o: {},
    },
  },
];

const HEADER = [
  "Cross-language post-quantum test vectors for Activeledger SDKs.",
  "",
  "Generated by scripts/pq-vectors.mjs from the JavaScript SDK, which is the",
  "reference implementation. Do not hand-edit.",
  "",
  "What gets signed is `message` exactly as given, encoded UTF-8. There is no",
  "hash prefix, no length prefix, no domain separator and no key sorting.",
  "",
  "THE RULE, FOR BOTH SCHEMES: verify these signatures, round-trip these key",
  "bytes, and never expect your own signature over the same message to equal",
  "the one published here.",
  "",
  "ml-dsa-65 is HEDGED in this SDK, not deterministic. packages/node/src/",
  "crypto.ts passes fresh extraEntropy on every sign - deliberately, so the",
  "library does not depend on globalThis.crypto.getRandomValues being present",
  "and unmodified in someone else's process. FIPS 204 permits both; a bare",
  "key would give rnd = 0^32 and be deterministic, and this SDK does not do",
  "that. Signing the same message twice here produces two different, equally",
  "valid signatures. A port should be hedged too, seeded from its own secure",
  "RNG, and must not assert byte-equality against this file.",
  "",
  "falcon-512 is also non-reproducible, for a second reason: its key",
  "generation is implementation-specific, so the same seed does not give the",
  "same key in a different library. Falcon signature length varies too",
  "(649-662 bytes observed); nothing may assume it fixed.",
  "",
  "Falcon key bytes here INCLUDE the 1-byte type header (0x09 public, 0x59",
  "private), so they are 897 and 1281 bytes. BouncyCastle's raw getters strip",
  "that header and return 896/1280 - a JVM port must add it back on export.",
].join("\n");

const EXPECTED = {
  "ml-dsa-65": { pub: 1952, prv: 4032, sig: 3309 },
  "falcon-512": { pub: 897, prv: 1281, sig: null },
};

const b64len = (s) => Buffer.from(s, "base64").length;

const vectors = [];

for (const type of TYPES) {
  const want = EXPECTED[type];

  for (const message of MESSAGES) {
    const key = provider.generate(undefined, type);

    // The onboard case carries its own public key, so build the object with
    // the real value before serialising. This is also the shape a port sends
    // first, and getting it wrong is the most common first failure.
    const tx = JSON.parse(JSON.stringify(message.tx));
    if (tx.$i?.identity?.publicKey === "PLACEHOLDER") {
      tx.$i.identity.type = type;
      tx.$i.identity.publicKey = key.pub.pkcs8pem;
    }

    const serialised = JSON.stringify(tx);
    const signature = provider.sign(serialised, key.prv, type);

    // Fail loudly at generation rather than publishing a bad vector that
    // every port then inherits as gospel.
    if (b64len(key.pub.pkcs8pem) !== want.pub) {
      throw new Error(`${type} public key is ${b64len(key.pub.pkcs8pem)} bytes, expected ${want.pub}`);
    }
    if (b64len(key.prv.pkcs8pem) !== want.prv) {
      throw new Error(`${type} private key is ${b64len(key.prv.pkcs8pem)} bytes, expected ${want.prv}`);
    }
    const sigBytes = b64len(signature);
    if (want.sig !== null && sigBytes !== want.sig) {
      throw new Error(`${type} signature is ${sigBytes} bytes, expected ${want.sig}`);
    }
    if (want.sig === null && (sigBytes < 649 || sigBytes > 662)) {
      throw new Error(`${type} signature is ${sigBytes} bytes, outside the expected 649-662`);
    }
    if (!provider.verify(serialised, signature, key.pub, type)) {
      throw new Error(`${type} / ${message.name}: generated signature does not verify`);
    }

    vectors.push({
      type,
      messageName: message.name,
      message: serialised,
      messageBytes: Buffer.from(serialised, "utf8").length,
      publicKey: key.pub.pkcs8pem,
      publicKeyBytes: want.pub,
      privateKey: key.prv.pkcs8pem,
      privateKeyBytes: want.prv,
      signature,
      signatureBytes: sigBytes,
    });
  }
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  JSON.stringify({ header: HEADER, generated: TYPES, vectors }, null, 2) + "\n"
);

console.log(`Wrote ${vectors.length} vectors to ${path.relative(process.cwd(), OUT)}`);
for (const type of TYPES) {
  const n = vectors.filter((v) => v.type === type).length;
  console.log(`  ${type}: ${n}`);
}
