// Generates the cross-language post-quantum test vectors that every
// non-JavaScript SDK checks itself against.
//
// The JS SDK is the reference implementation, so "correct" for a port means
// "agrees with this file". Publishing it as a committed artefact is what
// stops each port defining correctness by accident, and what lets a port
// author work without a running ledger.
//
// Regenerate with: npm run vectors
//
// KEY BYTES, NOT SEEDS - this matters and is not an arbitrary choice.
// ml-dsa-65 derives its key pair deterministically from a 32-byte seed, so a
// seed would be enough for it. falcon-512 does NOT: its key generation is
// implementation-specific, so the same seed produces different keys in
// different libraries. A seed-based vector file would therefore be unusable
// from Kotlin, Python or Go, which is precisely who it is for.

import { createRequire } from "module";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const { NodeCryptoProvider } = require("../packages/node/lib/index.js");
const { WebCryptoProvider } = require("../packages/web/lib/crypto.js");

const provider = new NodeCryptoProvider();

// sdk-web signs through @noble/curves, which is RFC 6979 deterministic and
// normalises to low-S. sdk-node signs through OpenSSL, which is neither. Both
// are valid and the ledger accepts both, so the file publishes both: the
// OpenSSL one to prove a port's VERIFICATION copes with high-S, and the noble
// one as the exact bytes a conforming SIGNER must reproduce.
const deterministicProvider = new WebCryptoProvider();
const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, "..", "vectors", "pq-vectors.json");

const PQ_TYPES = ["ml-dsa-65", "falcon-512"];

// secp256k1 is generated in both public key forms, because the ledger
// accepts either and a port has to read both. Its key encoding is nothing
// like the post-quantum one - see the header written into the file.
const EC_FORMS = [
  { form: "compressed", compressed: true, pubChars: 68 },
  { form: "uncompressed", compressed: false, pubChars: 132 },
];

// Regenerating a type replaces every one of its vectors, and the published
// signatures are what six SDK repositories check themselves against. So a
// type is only rewritten when it is asked for by name.
//   node scripts/pq-vectors.mjs                  -> everything
//   node scripts/pq-vectors.mjs secp256k1        -> only secp256k1
const REQUESTED = process.argv.slice(2);
const wanted = (type) => REQUESTED.length === 0 || REQUESTED.includes(type);

// Each case is a $tx object. What actually gets signed is
// JSON.stringify($tx) encoded UTF-8 - no hash prefix, no length prefix, no
// key sorting - so these are chosen to catch the canonicalisation bugs that
// an ASCII-only integer payload cannot.
const MESSAGES = [
  // Baseline. Passes in every language even when everything below is broken.
  { name: "ascii", tx: { greeting: "hello" } },

  // Catches Python's json.dumps(ensure_ascii=True), which would emit \uXXXX
  // escapes and sign different bytes. An accented Latin letter, a CJK
  // character and an emoji - 2, 3 and 4 byte UTF-8 sequences respectively.
  { name: "non-ascii", tx: { greeting: "café 日本語 ☕" } },

  // Catches Go's encoding/json, which HTML-escapes <, > and & by default,
  // and any JVM JSON library configured the same way.
  { name: "html", tx: { expr: "a < b && c > d", amp: "Tom & Jerry" } },

  // Catches number formatting. JavaScript prints 1, not 1.0.
  { name: "float", tx: { whole: 1.0, third: 0.1, negative: -2.5, zero: 0 } },

  // Catches key reordering. The ledger does not canonicalise key order, so a
  // signer must reproduce insertion order exactly. These keys are
  // deliberately NOT alphabetical - a library that sorts will fail here.
  { name: "ordering", tx: { zebra: 1, alpha: 2, middle: 3 } },

  // A realistic onboarding body, closest to what a port sends first.
  {
    name: "onboard",
    tx: {
      $namespace: "default",
      $contract: "onboard",
      $i: { identity: { type: "ml-dsa-65", publicKey: "PLACEHOLDER" } },
      $o: {},
    },
  },
];

const HEADER = [
  "Cross-language test vectors for Activeledger SDKs.",
  "",
  "The file name is historical: it now covers secp256k1 as well as the two",
  "post-quantum schemes. Filter by `type`.",
  "",
  "Generated by scripts/pq-vectors.mjs from the JavaScript SDK, which is the",
  "reference implementation. Do not hand-edit.",
  "",
  "What gets signed is `message` exactly as given, encoded UTF-8. There is no",
  "hash prefix, no length prefix, no domain separator and no key sorting.",
  "",
  "THE RULE, FOR ALL THREE SCHEMES: verify these signatures, round-trip these",
  "key bytes, and never expect your own signature over the same message to",
  "equal the one published here.",
  "",
  "ml-dsa-65 is HEDGED in this SDK, not deterministic. packages/node/src/",
  "crypto.ts passes fresh extraEntropy on every sign - deliberately, so the",
  "library does not depend on globalThis.crypto.getRandomValues being present",
  "and unmodified in someone else's process. FIPS 204 permits both; a bare",
  "key would give rnd = 0^32 and be deterministic, and this SDK does not do",
  "that. Signing the same message twice here produces two different, equally",
  "valid signatures. A port should be hedged too, seeded from its own secure",
  "RNG, and must not assert byte-equality against this file.",
  "",
  "falcon-512 is also non-reproducible, for a second reason: its key",
  "generation is implementation-specific, so the same seed does not give the",
  "same key in a different library. Falcon signature length varies too",
  "(649-662 bytes observed); nothing may assume it fixed.",
  "",
  "Falcon key bytes here INCLUDE the 1-byte type header (0x09 public, 0x59",
  "private), so they are 897 and 1281 bytes. BouncyCastle's raw getters strip",
  "that header and return 896/1280 - a JVM port must add it back on export.",
  "",
  "SECP256K1 IS ENCODED COMPLETELY DIFFERENTLY, and reusing the post-quantum",
  "path for it is the mistake this section exists to prevent:",
  "",
  "  - Keys are 0x-PREFIXED HEX, not base64. Public keys appear in both forms",
  "    the ledger accepts: compressed (33 bytes, 68 chars) and uncompressed",
  "    (65 bytes, 132 chars). `publicKeyForm` says which. Private keys are 32",
  "    bytes, 66 chars.",
  "",
  "  - Private keys are LEFT-PADDED to 32 bytes. node's ECDH.getPrivateKey()",
  "    strips leading zero bytes, which happens to roughly 1 key in 400; the",
  "    shorter string is a different scalar to anything that reads it",
  "    strictly. A port must pad, not trust its library.",
  "",
  "  - Signatures are SHA-256 then ECDSA then DER, and the DER bytes are what",
  "    gets base64-encoded into $sigs. DER LENGTH VARIES - 70, 71 and 72 bytes",
  "    are all common. Nothing may assume it fixed.",
  "",
  "  - DO NOT enforce low-S when verifying. The ledger verifies through",
  "    OpenSSL, which does not normalise S, so it both produces and accepts",
  "    high-S signatures. Producing low-S is fine and still verifies;",
  "    REJECTING high-S would reject signatures the ledger itself made.",
  "",
  "  - THREE signatures are published per secp256k1 vector. `signature` comes",
  "    from OpenSSL: a random k and whatever S it lands on, which is what the",
  "    ledger itself produces, so a port's VERIFICATION must accept it -",
  "    including the high-S ones. `deterministicSignature` is RFC 6979 with S",
  "    normalised low, and is the exact output a conforming SIGNER must",
  "    reproduce byte for byte. `highSSignature` is that same signature with s",
  "    negated - still valid, still verifying under the same key, and",
  "    guaranteed non-canonical. A port's verification MUST accept it.",
  "",
  "    That last one is published as bytes rather than left to each port to",
  "    build, because the construction needs the curve order: a port that",
  "    sources n from the wrong place produces a fixture that is simply",
  "    invalid, and which then passes a permissive verifier for the wrong",
  "    reason - green, and proving nothing.",
  "",
  "  - So the rule at the top - verify, never compare - applies in full to the",
  "    post-quantum schemes, which are hedged, but only to `signature` here.",
  "    Compare your signer against `deterministicSignature`: ECDSA has no",
  "    reason to be hedged, and an exact comparison catches a low-S mistake",
  "    that a verify-round-trip test cannot see at all.",
  "",
  "  - The ledger also accepts the type strings `bitcoin` and `ethereum`,",
  "    routed to identical secp256k1 verification. Ports should parse them as",
  "    secp256k1 and never emit them.",
].join("\n");

const EXPECTED = {
  "ml-dsa-65": { pub: 1952, prv: 4032, sig: 3309 },
  "falcon-512": { pub: 897, prv: 1281, sig: null },
};

const b64len = (s) => Buffer.from(s, "base64").length;

// secp256k1's group order, and the halfway point that divides "low S" from
// "high S".
const SECP256K1_N = BigInt("0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141");
const SECP256K1_HALF_N = SECP256K1_N / 2n;

/**
 * Pulls S out of a DER ECDSA signature.
 *
 * Only needed to tell high-S signatures from low-S ones, which matters more
 * than it sounds: several libraries REJECT high-S by default (@noble/curves
 * and libsecp256k1 among them), while the ledger verifies through OpenSSL,
 * which neither normalises nor requires it. A port that inherits its
 * library's default silently rejects about half of all valid ledger
 * signatures - an intermittent failure that looks like anything but a
 * configuration flag.
 */
function derSignatureS(der) {
  let i = 2;
  if (der[i] !== 0x02) throw new Error("malformed DER: expected R");
  i += 2 + der[i + 1];
  if (der[i] !== 0x02) throw new Error("malformed DER: expected S");
  const s = der.subarray(i + 2, i + 2 + der[i + 1]);
  return BigInt("0x" + Buffer.from(s).toString("hex"));
}

const isHighS = (signatureBase64) =>
  derSignatureS(Buffer.from(signatureBase64, "base64")) > SECP256K1_HALF_N;

/**
 * Builds the high-S form of a signature by negating s.
 *
 * `(r, s)` and `(r, n - s)` are both valid signatures over the same message
 * under the same public key -- that is ECDSA malleability, and it is exactly
 * the property being tested. So no signing and no private key is needed, and
 * the case is available for EVERY vector rather than the subset a random k
 * happened to land high.
 *
 * Published as bytes rather than left to each port to construct. The
 * construction needs the curve order, and a port that sources n from the
 * wrong place produces a fixture that is simply invalid -- which then passes
 * a permissive verifier for the wrong reason, proving nothing while looking
 * green.
 */
function toHighS(signatureBase64) {
  const der = Buffer.from(signatureBase64, "base64");

  let i = 2;
  if (der[i] !== 0x02) throw new Error("malformed DER: expected R");
  const rLength = der[i + 1];
  const r = der.subarray(i + 2, i + 2 + rLength);

  i += 2 + rLength;
  if (der[i] !== 0x02) throw new Error("malformed DER: expected S");
  const s = BigInt("0x" + Buffer.from(der.subarray(i + 2, i + 2 + der[i + 1])).toString("hex"));

  return encodeDer(r, SECP256K1_N - s);
}

/** DER INTEGER: minimal length, leading zero when the top bit is set. */
function derInteger(bytes) {
  let value = Buffer.from(bytes);
  let start = 0;
  while (start < value.length - 1 && value[start] === 0) start++;
  value = value.subarray(start);
  if (value[0] & 0x80) value = Buffer.concat([Buffer.from([0]), value]);

  return Buffer.concat([Buffer.from([0x02, value.length]), value]);
}

function encodeDer(r, s) {
  const sBytes = Buffer.from(s.toString(16).padStart(64, "0"), "hex");
  const body = Buffer.concat([derInteger(r), derInteger(sBytes)]);

  return Buffer.concat([Buffer.from([0x30, body.length]), body]).toString("base64");
}


const vectors = [];

for (const type of PQ_TYPES.filter(wanted)) {
  const want = EXPECTED[type];

  for (const message of MESSAGES) {
    const key = provider.generate(undefined, type);

    // The onboard case carries its own public key, so build the object with
    // the real value before serialising. This is also the shape a port sends
    // first, and getting it wrong is the most common first failure.
    const tx = JSON.parse(JSON.stringify(message.tx));
    if (tx.$i?.identity?.publicKey === "PLACEHOLDER") {
      tx.$i.identity.type = type;
      tx.$i.identity.publicKey = key.pub.pkcs8pem;
    }

    const serialised = JSON.stringify(tx);
    const signature = provider.sign(serialised, key.prv, type);

    // Fail loudly at generation rather than publishing a bad vector that
    // every port then inherits as gospel.
    if (b64len(key.pub.pkcs8pem) !== want.pub) {
      throw new Error(`${type} public key is ${b64len(key.pub.pkcs8pem)} bytes, expected ${want.pub}`);
    }
    if (b64len(key.prv.pkcs8pem) !== want.prv) {
      throw new Error(`${type} private key is ${b64len(key.prv.pkcs8pem)} bytes, expected ${want.prv}`);
    }
    const sigBytes = b64len(signature);
    if (want.sig !== null && sigBytes !== want.sig) {
      throw new Error(`${type} signature is ${sigBytes} bytes, expected ${want.sig}`);
    }
    if (want.sig === null && (sigBytes < 649 || sigBytes > 662)) {
      throw new Error(`${type} signature is ${sigBytes} bytes, outside the expected 649-662`);
    }
    if (!provider.verify(serialised, signature, key.pub, type)) {
      throw new Error(`${type} / ${message.name}: generated signature does not verify`);
    }

    vectors.push({
      type,
      keyEncoding: "base64",
      signatureFormat: "raw",
      messageName: message.name,
      message: serialised,
      messageBytes: Buffer.from(serialised, "utf8").length,
      publicKey: key.pub.pkcs8pem,
      publicKeyBytes: want.pub,
      privateKey: key.prv.pkcs8pem,
      privateKeyBytes: want.prv,
      signature,
      signatureBytes: sigBytes,
    });
  }
}

// ---------------------------------------------------------------------------
// secp256k1
//
// Everything about its encoding differs from the post-quantum schemes, which
// is the whole reason these vectors exist: a port that reuses its base64 key
// path here produces garbage that fails as 1220 and says nothing else.
// ---------------------------------------------------------------------------
if (wanted("secp256k1")) {
  for (const { form, compressed, pubChars } of EC_FORMS) {
    for (const message of MESSAGES) {
      const key = provider.generate(compressed, "secp256k1");

      const tx = JSON.parse(JSON.stringify(message.tx));
      if (tx.$i?.identity?.publicKey === "PLACEHOLDER") {
        tx.$i.identity.type = "secp256k1";
        tx.$i.identity.publicKey = key.pub.pkcs8pem;
      }

      const serialised = JSON.stringify(tx);
      const signature = provider.sign(serialised, key.prv, "secp256k1");
      const sigBytes = b64len(signature);

      // What a conforming signer must produce, byte for byte.
      const deterministicSignature = deterministicProvider.sign(serialised, key.prv, "secp256k1");
      if (deterministicSignature !== deterministicProvider.sign(serialised, key.prv, "secp256k1")) {
        throw new Error("secp256k1: the deterministic signer is not deterministic");
      }
      if (isHighS(deterministicSignature)) {
        throw new Error("secp256k1: the deterministic signature is high-S, it must be normalised");
      }
      if (!provider.verify(serialised, deterministicSignature, key.pub, "secp256k1")) {
        throw new Error("secp256k1: the deterministic signature does not verify under OpenSSL");
      }

      // Fail loudly at generation rather than publishing a bad vector that
      // every port then inherits as gospel.
      if (key.pub.pkcs8pem.length !== pubChars) {
        throw new Error(
          `secp256k1 ${form} public key is ${key.pub.pkcs8pem.length} chars, expected ${pubChars}`
        );
      }
      // 66 = "0x" + 64 hex. node's ECDH.getPrivateKey() strips leading zero
      // bytes (about 1 key in 400), so a port that does not left-pad back to
      // 32 bytes will emit a shorter string that other implementations read
      // as a different scalar.
      if (key.prv.pkcs8pem.length !== 66) {
        throw new Error(
          `secp256k1 private key is ${key.prv.pkcs8pem.length} chars, expected 66 - left-padding is missing`
        );
      }
      if (!key.pub.pkcs8pem.startsWith("0x") || !key.prv.pkcs8pem.startsWith("0x")) {
        throw new Error("secp256k1 keys must carry the 0x prefix the ledger stores");
      }
      // DER is variable length. 70-72 covers what random k produces in
      // practice; a shorter one is legal but worth knowing about.
      if (sigBytes < 64 || sigBytes > 72) {
        throw new Error(`secp256k1 DER signature is ${sigBytes} bytes, outside the expected 64-72`);
      }
      if (!provider.verify(serialised, signature, key.pub, "secp256k1")) {
        throw new Error(`secp256k1 / ${message.name}: generated signature does not verify`);
      }

      // The same signature with s negated: still valid, still verifies under
      // the same key, and guaranteed non-canonical.
      const highSSignature = toHighS(deterministicSignature);

      if (highSSignature === deterministicSignature) {
        throw new Error("secp256k1: negating s produced the same signature");
      }
      if (!isHighS(highSSignature)) {
        throw new Error(
          "secp256k1: the negated signature is not high-S. If the source was " +
            "already high-S this produces the LOW form, which would make the " +
            "fixture a silent duplicate of the low-S case."
        );
      }
      if (!provider.verify(serialised, highSSignature, key.pub, "secp256k1")) {
        throw new Error("secp256k1: the high-S signature does not verify");
      }

      vectors.push({
        type: "secp256k1",
        keyEncoding: "hex-0x",
        signatureFormat: "der",
        publicKeyForm: form,
        messageName: message.name,
        message: serialised,
        messageBytes: Buffer.from(serialised, "utf8").length,
        publicKey: key.pub.pkcs8pem,
        publicKeyBytes: compressed ? 33 : 65,
        privateKey: key.prv.pkcs8pem,
        privateKeyBytes: 32,
        signature,
        signatureBytes: sigBytes,
        deterministicSignature,
        highSSignature,
      });
    }
  }
}

// Both S forms must appear among the secp256k1 vectors, or the file stops
// catching the single most expensive mistake a port can make here. Random k
// gives roughly a 50/50 split, so this is nearly always satisfied - but
// "nearly always" is not a property to leave to chance in a file six SDKs
// treat as the definition of correct.
if (wanted("secp256k1")) {
  const ec = vectors.filter((v) => v.type === "secp256k1");
  const high = ec.filter((v) => isHighS(v.signature)).length;
  const low = ec.length - high;
  if (high === 0 || low === 0) {
    throw new Error(
      `secp256k1 vectors must include both high-S and low-S signatures, got ` +
        `${high} high and ${low} low. Re-run to draw a different k.`
    );
  }
  console.log(`  secp256k1 S split: ${high} high, ${low} low`);
}

// Keep every vector for a type that was not regenerated this run. The
// published signatures are what six SDK repositories check themselves
// against, so rewriting one by accident silently invalidates their copies.
if (fs.existsSync(OUT)) {
  const existing = JSON.parse(fs.readFileSync(OUT, "utf8")).vectors ?? [];
  const regenerated = new Set(vectors.map((v) => v.type));
  const kept = existing.filter((v) => !regenerated.has(v.type)).map((v) => ({
    // Backfill metadata added after these vectors were first published.
    // Descriptive only - it says how to read the bytes, it does not change
    // them, so the published signatures stay exactly as they were.
    keyEncoding: "base64",
    signatureFormat: "raw",
    ...v,
  }));
  vectors.unshift(...kept);
}

// Stable order: post-quantum first, then secp256k1. Ports look messages up
// by name, and the first match must stay the one they already resolve to.
const ORDER = ["ml-dsa-65", "falcon-512", "secp256k1"];
vectors.sort((a, b) => ORDER.indexOf(a.type) - ORDER.indexOf(b.type));

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  JSON.stringify({ header: HEADER, generated: [...new Set(vectors.map((v) => v.type))], vectors }, null, 2) + "\n"
);

console.log(`Wrote ${vectors.length} vectors to ${path.relative(process.cwd(), OUT)}`);
for (const type of [...new Set(vectors.map((v) => v.type))]) {
  const n = vectors.filter((v) => v.type === type).length;
  console.log(`  ${type}: ${n}`);
}
