/*
 * MIT License (MIT)
 * Copyright (c) 2019 Activeledger
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { IKey } from "@activeledger/sdk-core";

// "A file" is a Node-only concept, so this lives here rather than in
// sdk-core alongside the other transaction/key interfaces.
export interface IKeyExportOptions {
  location: string;
  createDir?: boolean;
  overwrite?: boolean;
  name?: string;
}

// Extends IKey with the BIP-39 recovery phrase - kept local to this
// package (duplicated in sdk-web too) rather than added to sdk-core, since
// the BIP-39 feature itself lives entirely in the platform packages.
export interface IKeyExtended extends IKey {
  phrase?: string;
}

// (duplicated in sdk-web too, alongside IKeyExtended)
export interface IBIP39Options {
  compressed?: boolean;
  /** Optional BIP-39 passphrase ("25th word"). Ignored when legacy is true. */
  passphrase?: string;
  /**
   * Use the original @activeledger/sdk-bip39 package's scheme -
   * SHA256(phrase) directly as the private key, no KDF, no domain
   * separation - instead of the standard BIP-39 seed + BIP-32 master-key
   * derivation used by default. Only for recovering a phrase that was
   * already generated by that package; do not use it for new keys.
   */
  legacy?: boolean;
}
