/*
 * MIT License (MIT)
 * Copyright (c) 2019 Activeledger
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import * as crypto from "crypto";
import * as fs from "fs";
import { generateMnemonic, mnemonicToSeedSync } from "bip39";
import { IKey, KeyHandler as CoreKeyHandler, KeyType } from "@activeledger/sdk-core";
import { IBIP39Options, IKeyExportOptions, IKeyExtended } from "./interfaces";
import { NodeCryptoProvider } from "./crypto";
import { deriveSeed, validate } from "./recovery";

/**
 * Adds file-based key import/export, and BIP-39 recovery-phrase key
 * generation, to the core KeyHandler.
 *
 * @export
 * @class KeyHandler
 */
export class KeyHandler extends CoreKeyHandler {
  /** Kept here as well as passed up, since the base class holds it privately. */
  private readonly provider: NodeCryptoProvider;

  constructor() {
    const provider = new NodeCryptoProvider();
    super(provider);
    this.provider = provider;
  }

  /**
   * Generate a new key with a BIP-39 recovery phrase.
   *
   * @param {string} keyName - The name of the key
   * @param {IBIP39Options} [options]
   * @returns {Promise<IKeyExtended>}
   * @memberof KeyHandler
   */
  public generateBIP39Key(keyName: string, options?: IBIP39Options): Promise<IKeyExtended> {
    return this.restoreBIP39Key(keyName, generateMnemonic(), options);
  }

  /**
   * Recreate a key from a previously generated BIP-39 recovery phrase.
   *
   * By default, the private key is derived the standard way - a BIP-39
   * PBKDF2 seed, then just the BIP-32 master-key step (HMAC-SHA512 keyed
   * with "Bitcoin seed", left 32 bytes) - deliberately stopping there
   * rather than doing any further hierarchical (HD) child derivation,
   * since Activeledger attaches many independent keys to one identity
   * rather than deriving them from a single tree.
   *
   * `options.legacy: true` instead reproduces the original
   * @activeledger/sdk-bip39 package's scheme - SHA256(phrase) used
   * directly as the private key, with no KDF or domain separation - only
   * for recovering a phrase that was already generated by that package.
   * Do not use it for new keys.
   *
   * @param {string} keyName - The name of the key
   * @param {string} phrase - The recovery phrase
   * @param {IBIP39Options} [options]
   * @returns {Promise<IKeyExtended>}
   * @memberof KeyHandler
   */
  public restoreBIP39Key(keyName: string, phrase: string, options: IBIP39Options = {}): Promise<IKeyExtended> {
    return new Promise((resolve, reject) => {
      try {
        const type = options.type || KeyType.EllipticCurve;

        if (options.legacy && type !== KeyType.EllipticCurve) {
          // The legacy scheme produces a 32-byte scalar and nothing else.
          // Silently ignoring it for a post-quantum type would hand back a
          // key from the modern derivation while the caller believed they
          // were recovering an old one.
          return reject(
            new Error(`The legacy BIP-39 scheme is secp256k1 only - it cannot derive ${type}`)
          );
        }

        // legacy: the same SHA256(phrase) scheme @activeledger/sdk-bip39
        // always used, byte-for-byte the same derived scalar. Leading zero
        // bytes don't change the integer value a hex string encodes, only
        // its string length, so zero-padding the *output* to 32 bytes below
        // doesn't change which key this derives for a given phrase - it
        // only avoids handing back a non-standard-length string that
        // @noble/curves (used by sdk-web) hard-rejects outright rather than
        // reinterpreting leniently the way node:crypto/OpenSSL do.
        // Validated unless explicitly waived. An unchecked phrase does not
        // fail loudly: a typo lands on a different VALID key for an identity
        // nobody owns, and the only symptom is the ledger not recognising it
        // - a long way from the cause. Every other Activeledger SDK checks
        // here, and this package was the last that did not.
        //
        // Not applied to the legacy scheme, which is SHA256 of the string and
        // never a BIP-39 mnemonic operation. The original
        // @activeledger/sdk-bip39 package never consulted the wordlist, so
        // refusing a phrase it accepted would make a recoverable identity
        // unrecoverable.
        if (!options.legacy && options.validate !== false) {
          validate(phrase);
        }

        const seed = options.legacy
          ? crypto.createHash("sha256").update(phrase, "utf8").digest()
          : deriveSeed(type, mnemonicToSeedSync(phrase, options.passphrase || ""));

        const keyHolder: IKeyExtended = {
          key: this.provider.generateFromSeed(seed, options.compressed, type),
          name: keyName,
          type,
          phrase,
        };

        resolve(keyHolder);
      } catch (error) {
        reject(error);
      }
    });
  }



  /**
   * Export a key to a file
   *
   * @param {IKey} key - The key to export
   * @param {IKeyExportOptions} options - The configuration options for the export
   * @returns {Promise<void>}
   * @memberof KeyHandler
   */
  public exportKey(key: IKey, options: IKeyExportOptions): Promise<void>;
  /**
   *
   *
   * @param {IKey} key
   * @param {string} location - The location to save the key to
   * @param {boolean} [createDir] - (Optional) Create the directory structure
   * @param {boolean} [overwrite] - (Optional) Overwrite an existing file if it exists
   * @param {string} [name] - (Optional) - Set a name for the file
   * @returns {Promise<void>}
   * @memberof KeyHandler
   */
  public exportKey(
    key: IKey,
    location: string,
    createDir?: boolean,
    overwrite?: boolean,
    name?: string,
  ): Promise<void>;
  public exportKey(
    key: IKey,
    locationOrOptions: string | IKeyExportOptions,
    createDir?: boolean,
    overwrite?: boolean,
    name?: string,
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const setOptions = (): IKeyExportOptions => {
        return {
          createDir: createDir ? true : false,
          location: locationOrOptions as string,
          name,
          overwrite: overwrite ? true : false,
        };
      };

      const options: IKeyExportOptions =
        typeof locationOrOptions === "string" ? setOptions() : (locationOrOptions as IKeyExportOptions);

      // Recursively create dir
      if (options.createDir) {
        try {
          fs.mkdirSync(options.location, { recursive: true });
        } catch (err) {
          return reject(err);
        }
      }

      // Strip trailing /
      options.location = this.stripTrailing(options.location);

      // Set name of file
      const path = options.name ? `${options.location}/${options.name}.json` : `${options.location}/${key.name}.json`;

      // Check folder exists
      const dirExists = fs.existsSync(options.location);
      if (dirExists) {
        // Check if the file exists
        const fileExists = fs.existsSync(path);
        // If exists and overwrite is false
        if (fileExists && !options.overwrite) {
          reject("File already exists, set overwrite to true or use a different name");
        } else {
          // Write
          fs.writeFile(path, JSON.stringify(key), (error: NodeJS.ErrnoException | null) => {
            if (error) {
              reject(error);
            } else {
              resolve();
            }
          });
        }
      } else {
        reject("Unable to find location");
      }
    });
  }

  /**
   * Import a key from a file
   *
   * @param {string} path - The location of the key file
   * @returns {Promise<IKey>}
   * @memberof KeyHandler
   */
  public importKey(path: string): Promise<IKey> {
    return new Promise((resolve, reject) => {
      fs.exists(path, (fileExists: boolean) => {
        if (fileExists) {
          fs.readFile(path, (error: NodeJS.ErrnoException | null, buffer: Buffer) => {
            if (error) {
              reject(error);
            } else {
              const data = buffer.toString();
              resolve(JSON.parse(data) as IKey);
            }
          });
        } else {
          reject("File not found.");
        }
      });
    });
  }

  /**
   * Remove a trailing / from the location
   *
   * @private
   * @param {string} path - String to strip from
   * @returns {string}
   * @memberof KeyHandler
   */
  private stripTrailing(path: string): string {
    const lastChar = path.slice(path.length - 1, path.length);
    if (lastChar === "/") {
      return path.slice(0, path.length - 1);
    }
    return path;
  }
}
